version: "3.8"
services:
  website: 
    container_name: website
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - 7002:80
    networks:
      - nginxproxymanager_default
    restart: always
networks:
  nginxproxymanager_default:
    external: true
