# Stage 1 - Building image
FROM node:19-alpine3.16 as node

# set working direction (just a name for the project)
WORKDIR /app/

#package and package-lock.json both go in
COPY package.json ./
RUN npm install

COPY . .

RUN npm run build

# Stage 2 - Running image
FROM 'nginx:latest'

COPY --from=node /app/dist /usr/share/nginx/html

EXPOSE 80 443
CMD [ "nginx", "-g", "daemon off;" ]

